// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// message describing AiPlatformFloorSetting
public struct AiPlatformFloorSetting: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. If true, log Model Armor filter results to Cloud Logging.
  public var enableCloudLogging: Swift.Bool = Swift.Bool()

  /// enforcement type for Model Armor filters.
  public var enforcementType: OneOf_EnforcementType? = nil

  /// Initialize a new instance of `AiPlatformFloorSetting`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AiPlatformFloorSetting().with { $0.inspectOnly = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case inspectOnly = "inspectOnly"
    case inspectAndBlock = "inspectAndBlock"
    case enableCloudLogging = "enableCloudLogging"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.enableCloudLogging = try container.decode(Swift.Bool.self, forKey: .enableCloudLogging)

    var enforcementType: OneOf_EnforcementType? = nil
    let enforcementTypeCheckAndSet = {
      if enforcementType != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'enforcementType'"))
      }
      enforcementType = $0
    }
    if let inspectOnly = try container.decodeIfPresent(Swift.Bool.self, forKey: .inspectOnly) {
      try enforcementTypeCheckAndSet(.inspectOnly(inspectOnly))
    }
    if let inspectAndBlock = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .inspectAndBlock)
    {
      try enforcementTypeCheckAndSet(.inspectAndBlock(inspectAndBlock))
    }
    self.enforcementType = enforcementType
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.enableCloudLogging, forKey: .enableCloudLogging)

    if let choice = self.enforcementType {
      switch choice {
      case .inspectOnly(let value):
        try container.encode(value, forKey: .inspectOnly)
      case .inspectAndBlock(let value):
        try container.encode(value, forKey: .inspectAndBlock)
      }
    }
  }

  /// enforcement type for Model Armor filters.
  public enum OneOf_EnforcementType: Codable, Equatable, Sendable {
    /// Optional. If true, Model Armor filters will be run in inspect only mode.
    /// No action will be taken on the request.
    case inspectOnly(Swift.Bool)
    /// Optional. If true, Model Armor filters will be run in inspect and block
    /// mode. Requests that trip Model Armor filters will be blocked.
    case inspectAndBlock(Swift.Bool)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.modelarmor.v1.AiPlatformFloorSetting"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
