// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Represents Data item
public struct DataItem: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Either of text or bytes data.
  public var dataItem: OneOf_DataItem? = nil

  /// Initialize a new instance of `DataItem`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataItem().with { $0.text = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case text = "text"
    case byteItem = "byteItem"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var dataItem: OneOf_DataItem? = nil
    let dataItemCheckAndSet = {
      if dataItem != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'dataItem'"))
      }
      dataItem = $0
    }
    if let text = try container.decodeIfPresent(Swift.String.self, forKey: .text) {
      try dataItemCheckAndSet(.text(text))
    }
    if let byteItem = try container.decodeIfPresent(ByteDataItem?.self, forKey: .byteItem) {
      try dataItemCheckAndSet(.byteItem(byteItem))
    }
    self.dataItem = dataItem
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.dataItem {
      switch choice {
      case .text(let value):
        try container.encode(value, forKey: .text)
      case .byteItem(let value):
        try container.encode(value, forKey: .byteItem)
      }
    }
  }

  /// Either of text or bytes data.
  public enum OneOf_DataItem: Codable, Equatable, Sendable {
    /// Plaintext string data for sanitization.
    case text(Swift.String)
    /// Data provided in the form of bytes.
    indirect case byteItem(ByteDataItem?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.modelarmor.v1.DataItem"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
