// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWKT
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class ModelArmorLogging: ModelArmorStub {
    let inner: any ModelArmorStub
    let logger: Logger

    public init(_ inner: any ModelArmorStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-modelarmor-v1"
      logger[metadataKey: "gcp.client.service"] = "modelarmor"
      logger[metadataKey: "gcp.experimental.swift.client"] = "ModelArmor"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listTemplates(
      request: ListTemplatesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudModelArmorV1.ListTemplatesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listTemplates",
        action: {
          (r: ListTemplatesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudModelArmorV1.ListTemplatesResponse
          in
          return try await self.inner.listTemplates(request: r, options: o)
        })
    }

    public func getTemplate(
      request: GetTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudModelArmorV1.Template {
      try await self._intercept(
        request: request,
        options: options,
        name: "getTemplate",
        action: {
          (r: GetTemplateRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudModelArmorV1.Template
          in
          return try await self.inner.getTemplate(request: r, options: o)
        })
    }

    public func createTemplate(
      request: CreateTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudModelArmorV1.Template {
      try await self._intercept(
        request: request,
        options: options,
        name: "createTemplate",
        action: {
          (r: CreateTemplateRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudModelArmorV1.Template
          in
          return try await self.inner.createTemplate(request: r, options: o)
        })
    }

    public func updateTemplate(
      request: UpdateTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudModelArmorV1.Template {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateTemplate",
        action: {
          (r: UpdateTemplateRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudModelArmorV1.Template
          in
          return try await self.inner.updateTemplate(request: r, options: o)
        })
    }

    public func deleteTemplate(
      request: DeleteTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteTemplate",
        action: {
          (r: DeleteTemplateRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteTemplate(request: r, options: o)
        })
    }

    public func getFloorSetting(
      request: GetFloorSettingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudModelArmorV1.FloorSetting {
      try await self._intercept(
        request: request,
        options: options,
        name: "getFloorSetting",
        action: {
          (r: GetFloorSettingRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudModelArmorV1.FloorSetting
          in
          return try await self.inner.getFloorSetting(request: r, options: o)
        })
    }

    public func updateFloorSetting(
      request: UpdateFloorSettingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudModelArmorV1.FloorSetting {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateFloorSetting",
        action: {
          (r: UpdateFloorSettingRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudModelArmorV1.FloorSetting
          in
          return try await self.inner.updateFloorSetting(request: r, options: o)
        })
    }

    public func sanitizeUserPrompt(
      request: SanitizeUserPromptRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudModelArmorV1.SanitizeUserPromptResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "sanitizeUserPrompt",
        action: {
          (r: SanitizeUserPromptRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudModelArmorV1.SanitizeUserPromptResponse
          in
          return try await self.inner.sanitizeUserPrompt(request: r, options: o)
        })
    }

    public func sanitizeModelResponse(
      request: SanitizeModelResponseRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudModelArmorV1.SanitizeModelResponseResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "sanitizeModelResponse",
        action: {
          (r: SanitizeModelResponseRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudModelArmorV1.SanitizeModelResponseResponse
          in
          return try await self.inner.sanitizeModelResponse(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }
  }
}
