// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleCloudGax

extension Clients {
  protocol ModelArmorStub: Sendable {
    func listTemplates(
      request: ListTemplatesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudModelArmorV1.ListTemplatesResponse

    func getTemplate(
      request: GetTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudModelArmorV1.Template

    func createTemplate(
      request: CreateTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudModelArmorV1.Template

    func updateTemplate(
      request: UpdateTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudModelArmorV1.Template

    func deleteTemplate(
      request: DeleteTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func getFloorSetting(
      request: GetFloorSettingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudModelArmorV1.FloorSetting

    func updateFloorSetting(
      request: UpdateFloorSettingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudModelArmorV1.FloorSetting

    func sanitizeUserPrompt(
      request: SanitizeUserPromptRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudModelArmorV1.SanitizeUserPromptResponse

    func sanitizeModelResponse(
      request: SanitizeModelResponseRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudModelArmorV1.SanitizeModelResponseResponse

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location
  }
}
