// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Responsible AI Result.
public struct RaiFilterResult: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Reports whether the RAI filter was successfully executed or
  /// not.
  public var executionState: FilterExecutionState = FilterExecutionState()

  /// Optional messages corresponding to the result.
  /// A message can provide warnings or error details.
  /// For example, if execution state is skipped then this field provides
  /// related reason/explanation.
  public var messageItems: [MessageItem] = []

  /// Output only. Overall filter match state for RAI.
  /// Value is MATCH_FOUND if at least one RAI filter confidence level is
  /// equal to or higher than the confidence level defined in configuration.
  public var matchState: FilterMatchState = FilterMatchState()

  /// The map of RAI filter results where key is RAI filter type - either of
  /// "sexually_explicit", "hate_speech", "harassment", "dangerous", "violence",
  /// "sexually_suggestive".
  public var raiFilterTypeResults: [Swift.String: RaiFilterResult.RaiFilterTypeResult] = [:]

  /// Initialize a new instance of `RaiFilterResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RaiFilterResult().with { $0.executionState = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Detailed Filter result for each of the responsible AI Filter Types.
  public struct RaiFilterTypeResult: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Type of responsible AI filter.
    public var filterType: RaiFilterType = RaiFilterType()

    /// Confidence level identified for this RAI filter.
    public var confidenceLevel: DetectionConfidenceLevel = DetectionConfidenceLevel()

    /// Output only. Match state for this RAI filter.
    public var matchState: FilterMatchState = FilterMatchState()

    /// Initialize a new instance of `RaiFilterTypeResult`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RaiFilterTypeResult().with { $0.filterType = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.modelarmor.v1.RaiFilterResult.RaiFilterTypeResult"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.modelarmor.v1.RaiFilterResult"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
