// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Sanitization result after applying all the filters on input content.
public struct SanitizationResult: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Overall filter match state for Sanitization.
  /// The state can have below two values.
  ///
  /// 1) NO_MATCH_FOUND: No filters in configuration satisfy matching criteria.
  /// In other words, input passed all filters.
  ///
  /// 2) MATCH_FOUND: At least one filter in configuration satisfies matching.
  /// In other words, input did not pass one or more filters.
  public var filterMatchState: FilterMatchState = FilterMatchState()

  /// Output only. Results for all filters where the key is the filter name -
  /// either of "csam", "malicious_uris", "rai", "pi_and_jailbreak" ,"sdp".
  public var filterResults: [Swift.String: FilterResult] = [:]

  /// Output only. A field indicating the outcome of the invocation, irrespective
  /// of match status. It can have the following three values: SUCCESS: All
  /// filters were executed successfully. PARTIAL: Some filters were skipped or
  /// failed execution. FAILURE: All filters were skipped or failed execution.
  public var invocationResult: InvocationResult = InvocationResult()

  /// Output only. Metadata related to Sanitization.
  public var sanitizationMetadata: SanitizationResult.SanitizationMetadata? = nil

  /// Initialize a new instance of `SanitizationResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SanitizationResult().with { $0.filterMatchState = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Message describing Sanitization metadata.
  public struct SanitizationMetadata: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Error code if any.
    public var errorCode: Swift.Int64 = Swift.Int64()

    /// Error message if any.
    public var errorMessage: Swift.String = Swift.String()

    /// Passthrough field defined in TemplateMetadata to indicate whether to
    /// ignore partial invocation failures.
    public var ignorePartialInvocationFailures: Swift.Bool = Swift.Bool()

    /// Output only. The stream chunk processed by the Sanitization service.
    public var streamChunkProcessed: DataItem? = nil

    /// Initialize a new instance of `SanitizationMetadata`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SanitizationMetadata().with { $0.errorCode = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.modelarmor.v1.SanitizationResult.SanitizationMetadata"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.modelarmor.v1.SanitizationResult"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
