// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Sensitive Data Protection Advanced configuration.
public struct SdpAdvancedConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Optional. Sensitive Data Protection inspect template resource name
  ///
  /// If only inspect template is provided (de-identify template not provided),
  /// then Sensitive Data Protection InspectContent action is performed during
  /// Sanitization. All Sensitive Data Protection findings identified during
  /// inspection will be returned as SdpFinding in SdpInsepctionResult.
  ///
  /// e.g.
  /// `projects/{project}/locations/{location}/inspectTemplates/{inspect_template}`
  public var inspectTemplate: Swift.String = Swift.String()

  /// Optional. Optional Sensitive Data Protection Deidentify template resource
  /// name.
  ///
  /// If provided then DeidentifyContent action is performed during Sanitization
  /// using this template and inspect template. The De-identified data will
  /// be returned in SdpDeidentifyResult.
  /// Note that all info-types present in the deidentify template must be present
  /// in inspect template.
  ///
  /// e.g.
  /// `projects/{project}/locations/{location}/deidentifyTemplates/{deidentify_template}`
  public var deidentifyTemplate: Swift.String = Swift.String()

  /// Initialize a new instance of `SdpAdvancedConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SdpAdvancedConfig().with { $0.inspectTemplate = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.modelarmor.v1.SdpAdvancedConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
