// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Precise location of the finding within a document, record, image, or
/// metadata container.
public struct SdpContentLocation: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Name of the container where the finding is located.
  /// The top level name is the source file name or table name.
  ///
  /// Nested names could be absent if the embedded object has no string
  /// identifier (for example, an image contained within a document).
  public var containerName: Swift.String = Swift.String()

  /// Type of the container within the file with location of the finding. This
  /// may be extended to include other container types like audio, video, etc in
  /// future.
  public var location: OneOf_Location? = nil

  /// Initialize a new instance of `SdpContentLocation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SdpContentLocation().with { $0.imageFindingLocation = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case imageFindingLocation = "imageFindingLocation"
    case containerName = "containerName"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.containerName = try container.decode(Swift.String.self, forKey: .containerName)

    var location: OneOf_Location? = nil
    let locationCheckAndSet = {
      if location != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'location'"))
      }
      location = $0
    }
    if let imageFindingLocation = try container.decodeIfPresent(
      SdpImageFindingLocation?.self, forKey: .imageFindingLocation)
    {
      try locationCheckAndSet(.imageFindingLocation(imageFindingLocation))
    }
    self.location = location
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.containerName, forKey: .containerName)

    if let choice = self.location {
      switch choice {
      case .imageFindingLocation(let value):
        try container.encode(value, forKey: .imageFindingLocation)
      }
    }
  }

  /// Type of the container within the file with location of the finding. This
  /// may be extended to include other container types like audio, video, etc in
  /// future.
  public enum OneOf_Location: Codable, Equatable, Sendable {
    /// Location within an image's pixels.
    indirect case imageFindingLocation(SdpImageFindingLocation?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.modelarmor.v1.SdpContentLocation"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
