// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Sensitive Data Protection settings.
public struct SdpFilterSettings: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Either of Sensitive Data Protection basic or advanced configuration.
  public var sdpConfiguration: OneOf_SdpConfiguration? = nil

  /// Initialize a new instance of `SdpFilterSettings`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SdpFilterSettings().with { $0.basicConfig = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case basicConfig = "basicConfig"
    case advancedConfig = "advancedConfig"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var sdpConfiguration: OneOf_SdpConfiguration? = nil
    let sdpConfigurationCheckAndSet = {
      if sdpConfiguration != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'sdpConfiguration'"))
      }
      sdpConfiguration = $0
    }
    if let basicConfig = try container.decodeIfPresent(SdpBasicConfig?.self, forKey: .basicConfig) {
      try sdpConfigurationCheckAndSet(.basicConfig(basicConfig))
    }
    if let advancedConfig = try container.decodeIfPresent(
      SdpAdvancedConfig?.self, forKey: .advancedConfig)
    {
      try sdpConfigurationCheckAndSet(.advancedConfig(advancedConfig))
    }
    self.sdpConfiguration = sdpConfiguration
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.sdpConfiguration {
      switch choice {
      case .basicConfig(let value):
        try container.encode(value, forKey: .basicConfig)
      case .advancedConfig(let value):
        try container.encode(value, forKey: .advancedConfig)
      }
    }
  }

  /// Either of Sensitive Data Protection basic or advanced configuration.
  public enum OneOf_SdpConfiguration: Codable, Equatable, Sendable {
    /// Optional. Basic Sensitive Data Protection configuration inspects the
    /// content for sensitive data using a fixed set of six info-types. Sensitive
    /// Data Protection templates cannot be used with basic configuration. Only
    /// Sensitive Data Protection inspection operation is supported with basic
    /// configuration.
    indirect case basicConfig(SdpBasicConfig?)
    /// Optional. Advanced Sensitive Data Protection configuration which enables
    /// use of Sensitive Data Protection templates. Supports both Sensitive Data
    /// Protection inspection and de-identification operations.
    indirect case advancedConfig(SdpAdvancedConfig?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.modelarmor.v1.SdpFilterSettings"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
