// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Finding corresponding to Sensitive Data Protection filter.
public struct SdpFinding: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Name of Sensitive Data Protection info type for this finding.
  public var infoType: Swift.String = Swift.String()

  /// Identified confidence likelihood for `info_type`.
  public var likelihood: SdpFindingLikelihood = SdpFindingLikelihood()

  /// Location for this finding.
  public var location: SdpFinding.SdpFindingLocation? = nil

  /// Initialize a new instance of `SdpFinding`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SdpFinding().with { $0.infoType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Location of this Sensitive Data Protection Finding within input content.
  public struct SdpFindingLocation: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Zero-based byte offsets delimiting the finding.
    /// These are relative to the finding's containing element.
    /// Note that when the content is not textual, this references
    /// the UTF-8 encoded textual representation of the content.
    /// Note: Omitted if content is an image.
    public var byteRange: RangeInfo? = nil

    /// Unicode character offsets delimiting the finding.
    /// These are relative to the finding's containing element.
    /// Provided when the content is text.
    /// Note: Omitted if content is an image.
    public var codepointRange: RangeInfo? = nil

    /// List of nested objects pointing to the precise location of the finding
    /// within an image, file or record.
    ///
    /// For example, a single finding might be detected in two
    /// separate bounding boxes within an image (e.g., if it wraps across
    /// a line or is partially obscured). In such cases, content_locations
    /// would contain two SdpContentLocation entries, each with an
    /// image_finding_location pointing to a different bounding box.
    public var contentLocations: [SdpContentLocation] = []

    /// Initialize a new instance of `SdpFindingLocation`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SdpFindingLocation().with { $0.byteRange = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.modelarmor.v1.SdpFinding.SdpFindingLocation"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.modelarmor.v1.SdpFinding"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
