// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Sensitive Data Protection Inspection Result.
public struct SdpInspectResult: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Reports whether Sensitive Data Protection inspection was
  /// successfully executed or not.
  public var executionState: FilterExecutionState = FilterExecutionState()

  /// Optional messages corresponding to the result.
  /// A message can provide warnings or error details.
  /// For example, if execution state is skipped then this field provides
  /// related reason/explanation.
  public var messageItems: [MessageItem] = []

  /// Output only. Match state for SDP Inspection.
  /// Value is MATCH_FOUND if at least one Sensitive Data Protection finding is
  /// identified.
  public var matchState: FilterMatchState = FilterMatchState()

  /// List of Sensitive Data Protection findings.
  public var findings: [SdpFinding] = []

  /// If true, then there is possibility that more findings were identified and
  /// the findings returned are a subset of all findings. The findings
  /// list might be truncated because the input items were too large, or because
  /// the server reached the maximum amount of resources allowed for a single API
  /// call.
  public var findingsTruncated: Swift.Bool = Swift.Bool()

  /// Contains text extracted from the image, if applicable.
  public var extractedImageText: Swift.String = Swift.String()

  /// Initialize a new instance of `SdpInspectResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SdpInspectResult().with { $0.executionState = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.modelarmor.v1.SdpInspectResult"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
