// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Sensitive Data Protection Redaction Result.
public struct SdpRedactResult: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Reports whether Sensitive Data Protection redaction was
  /// successfully executed or not.
  public var executionState: FilterExecutionState = FilterExecutionState()

  /// Output only. Optional messages corresponding to the result.
  /// A message can provide warnings or error details.
  /// For example, if execution state is skipped then this field provides
  /// related reason/explanation.
  public var messageItems: [MessageItem] = []

  /// Output only. Match state for Sensitive Data Protection Redaction.
  /// Value is MATCH_FOUND if content is redacted.
  public var matchState: FilterMatchState = FilterMatchState()

  /// Output only. The redacted image. The type will be the same as the original
  /// image.
  public var redactedImage: Foundation.Data = Foundation.Data()

  /// Output only. The findings. This field is populated in the response only
  /// when include_findings in the SDP template is set to true.
  public var findings: [SdpFinding] = []

  /// The extracted text from the image.
  public var extractedImageText: Swift.String = Swift.String()

  /// Initialize a new instance of `SdpRedactResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SdpRedactResult().with { $0.executionState = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.modelarmor.v1.SdpRedactResult"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
