// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Message describing Template resource
public struct Template: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identifier. name of resource
  public var name: Swift.String = Swift.String()

  /// Output only. [Output only] Create time stamp
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. [Output only] Update time stamp
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Optional. Labels as key value pairs
  public var labels: [Swift.String: Swift.String] = [:]

  /// Required. filter configuration for this template
  public var filterConfig: FilterConfig? = nil

  /// Optional. metadata for this template
  public var templateMetadata: Template.TemplateMetadata? = nil

  /// Initialize a new instance of `Template`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Template().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Message describing TemplateMetadata
  public struct TemplateMetadata: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Optional. If true, partial detector failures should be ignored.
    public var ignorePartialInvocationFailures: Swift.Bool = Swift.Bool()

    /// Optional. Indicates the custom error code set by the user to be returned
    /// to the end user by the service extension if the prompt trips Model Armor
    /// filters.
    public var customPromptSafetyErrorCode: Swift.Int32 = Swift.Int32()

    /// Optional. Indicates the custom error message set by the user to be
    /// returned to the end user if the prompt trips Model Armor filters.
    public var customPromptSafetyErrorMessage: Swift.String = Swift.String()

    /// Optional. Indicates the custom error code set by the user to be returned
    /// to the end user if the LLM response trips Model Armor filters.
    public var customLlmResponseSafetyErrorCode: Swift.Int32 = Swift.Int32()

    /// Optional. Indicates the custom error message set by the user to be
    /// returned to the end user if the LLM response trips Model Armor filters.
    public var customLlmResponseSafetyErrorMessage: Swift.String = Swift.String()

    /// Optional. If true, log template crud operations.
    public var logTemplateOperations: Swift.Bool = Swift.Bool()

    /// Optional. If true, log sanitize operations.
    public var logSanitizeOperations: Swift.Bool = Swift.Bool()

    /// Optional. Enforcement type for Model Armor filters.
    public var enforcementType: Template.TemplateMetadata.EnforcementType = Template
      .TemplateMetadata.EnforcementType()

    /// Optional. Metadata for multi language detection.
    public var multiLanguageDetection: Template.TemplateMetadata.MultiLanguageDetection? = nil

    /// Optional. Specifies the modalities to scan.
    /// If empty, only text modality will be scanned.
    public var modalities: [Modality] = []

    /// Initialize a new instance of `TemplateMetadata`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TemplateMetadata().with { $0.ignorePartialInvocationFailures = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Metadata to enable multi language detection via template.
    public struct MultiLanguageDetection: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// Required. If true, multi language detection will be enabled.
      public var enableMultiLanguageDetection: Swift.Bool = Swift.Bool()

      /// Initialize a new instance of `MultiLanguageDetection`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = MultiLanguageDetection().with { $0.enableMultiLanguageDetection = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.modelarmor.v1.Template.TemplateMetadata.MultiLanguageDetection"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    /// Enforcement type for Model Armor filters.
    public enum EnforcementType: Codable, Equatable, Sendable {
      /// Default value. Same as INSPECT_AND_BLOCK.
      case unspecified
      /// Model Armor filters will run in inspect only mode. No action will be
      /// taken on the request.
      case inspectOnly
      /// Model Armor filters will run in inspect and block mode. Requests
      /// that trip Model Armor filters will be blocked.
      case inspectAndBlock
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .inspectOnly: return 1
        case .inspectAndBlock: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "ENFORCEMENT_TYPE_UNSPECIFIED"
        case .inspectOnly: return "INSPECT_ONLY"
        case .inspectAndBlock: return "INSPECT_AND_BLOCK"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:EnforcementType/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "ENFORCEMENT_TYPE_UNSPECIFIED": self = .unspecified
        case "INSPECT_ONLY": self = .inspectOnly
        case "INSPECT_AND_BLOCK": self = .inspectAndBlock
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:EnforcementType/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .inspectOnly
        case 2: self = .inspectAndBlock
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .inspectOnly: return try container.encode(1)
        case .inspectAndBlock: return try container.encode(2)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.modelarmor.v1.Template.TemplateMetadata"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.modelarmor.v1.Template"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
