// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Details of an identified virus
public struct VirusDetail: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Name of vendor that produced this virus identification.
  public var vendor: Swift.String = Swift.String()

  /// Names of this Virus.
  public var names: [Swift.String] = []

  /// Threat type of the identified virus
  public var threatType: VirusDetail.ThreatType = VirusDetail.ThreatType()

  /// Initialize a new instance of `VirusDetail`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VirusDetail().with { $0.vendor = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Defines all the threat types of a virus
  public enum ThreatType: Codable, Equatable, Sendable {
    /// Unused
    case unspecified
    /// Unable to categorize threat
    case unknown
    /// Virus or Worm threat.
    case virusOrWorm
    /// Malicious program. E.g. Spyware, Trojan.
    case maliciousProgram
    /// Potentially harmful content. E.g. Injected code, Macro
    case potentiallyHarmfulContent
    /// Potentially unwanted content. E.g. Adware.
    case potentiallyUnwantedContent
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .unknown: return 1
      case .virusOrWorm: return 2
      case .maliciousProgram: return 3
      case .potentiallyHarmfulContent: return 4
      case .potentiallyUnwantedContent: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "THREAT_TYPE_UNSPECIFIED"
      case .unknown: return "UNKNOWN"
      case .virusOrWorm: return "VIRUS_OR_WORM"
      case .maliciousProgram: return "MALICIOUS_PROGRAM"
      case .potentiallyHarmfulContent: return "POTENTIALLY_HARMFUL_CONTENT"
      case .potentiallyUnwantedContent: return "POTENTIALLY_UNWANTED_CONTENT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ThreatType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "THREAT_TYPE_UNSPECIFIED": self = .unspecified
      case "UNKNOWN": self = .unknown
      case "VIRUS_OR_WORM": self = .virusOrWorm
      case "MALICIOUS_PROGRAM": self = .maliciousProgram
      case "POTENTIALLY_HARMFUL_CONTENT": self = .potentiallyHarmfulContent
      case "POTENTIALLY_UNWANTED_CONTENT": self = .potentiallyUnwantedContent
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ThreatType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .unknown
      case 2: self = .virusOrWorm
      case 3: self = .maliciousProgram
      case 4: self = .potentiallyHarmfulContent
      case 5: self = .potentiallyUnwantedContent
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .unknown: return try container.encode(1)
      case .virusOrWorm: return try container.encode(2)
      case .maliciousProgram: return try container.encode(3)
      case .potentiallyHarmfulContent: return try container.encode(4)
      case .potentiallyUnwantedContent: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.modelarmor.v1.VirusDetail"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
